language: java

jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: exasol

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.login=${SONAR_TOKEN}

cache:
  directories:
    - "$HOME/.m2"