language: java
matrix:
  include:
    - jdk: openjdk9
addons:
  sonarcloud:
    organization: exasol
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=com.exasol:virtual-schema-common-jdbc -Dsonar.login=${SONAR_TOKEN}
cache:
  directories:
    - "$HOME/.m2"